task1st
pashabetenya/OPEN-AREA pull request #3
Opened 2021-10-18 13:30 UTC by pashabetenya

check the code for readability.

2021-11-02 17:52 UTC, pashabetenya commented on lib/pages/authentication/login.dart
> +  Widget TitleText() {
this file no longer exists. rewrote it.

2021-11-02 17:52 UTC, pashabetenya commented on lib/pages/authentication/login.dart
> +    return Column(
this file no longer exists. rewrote it.

2021-11-02 18:39 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +              ClipPath(
made, put it in a separate file as a widget.

2021-11-02 20:10 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +                pageBuilder: (context, a, b) => LoginPage(),
corrected.

2021-11-02 20:20 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +  Widget _lineBetween() {
done.

2021-11-07 14:53 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +  Widget _emailTextFormField() {
done.

2021-11-08 13:08 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +  Widget _sendEmailMaterialButton() {
done.

2021-11-08 13:09 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +        height: 58,
done.

2021-11-10 13:51 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +      child: const Text('password_recovery',
done.

2021-11-10 13:53 UTC, pashabetenya commented on lib/ui/pages/profile_page.dart
> +                  context.locale = const Locale('en', 'US');
done.

2021-11-10 13:53 UTC, pashabetenya commented on lib/ui/widgets/navigation_widget.dart
> +import 'package:cryptocurrency/ui/pages/home_page.dart';
done.

2021-11-10 13:55 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +              SafeArea(
rewrote it differently, in a different way.

2021-11-14 20:03 UTC, qkul requested changes

2021-11-14 20:03 UTC, qkul commented on lib/ui/widgets/material_button_widget.dart
> +  final bool chColor;
what if we add another one color for the button?

2021-11-14 20:14 UTC, qkul commented on lib/ui/pages/forgot_password_page.dart
> +          child: Column(
wrap to SingleChildScrollView

2021-11-14 20:36 UTC, qkul commented on lib/ui/widgets/draw_clip_widget.dart
> +class DrawClipWidget extends StatefulWidget {
rename the widget without a word Widget: DrawClip

2021-11-14 20:43 UTC, qkul commented on lib/ui/widgets/draw_clip_widget.dart
> +import 'package:flutter/material.dart';
let's add file index.dart to lib/ui/widgets/index.dart. this file will be contains all export on this folder. and in the files where we will use widgets, we will import exactly lib/ui/widgets/index.dart

2021-11-15 15:13 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +        Align(
corrected.

2021-11-15 15:14 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +              )),
corrected.

2021-11-15 15:14 UTC, pashabetenya commented on lib/ui/pages/login_page.dart
> +                children: <Widget>[
corrected.

2021-11-15 15:14 UTC, pashabetenya commented on lib/ui/pages/login_page.dart
> +  Widget _buildLoginForm() {
corrected.

2021-11-15 15:14 UTC, pashabetenya commented on lib/ui/widgets/material_button_widget.dart
> +  final bool chColor;
corrected.

2021-11-15 15:15 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +          child: Column(
corrected.

2021-11-15 15:15 UTC, pashabetenya commented on lib/ui/widgets/draw_clip_widget.dart
> +class DrawClipWidget extends StatefulWidget {
corrected.

2021-11-15 15:58 UTC, qkul commented on lib/ui/pages/forgot_password_page.dart
> +        Align(
still not fixed

2021-11-15 15:59 UTC, qkul commented on lib/ui/pages/forgot_password_page.dart
> +              )),
still not fixed

2021-11-15 15:59 UTC, qkul commented on lib/ui/pages/login_page.dart
> +                children: <Widget>[
still not fixed

2021-11-16 15:44 UTC, pashabetenya commented on lib/ui/pages/login_page.dart
> +  Widget _titleTextOne() {
done.

2021-11-16 15:45 UTC, pashabetenya commented on lib/ui/pages/login_page.dart
> +                children: <Widget>[
all thinks done.

2021-11-16 15:46 UTC, pashabetenya commented on lib/ui/pages/login_page.dart
> +  Widget build(BuildContext context) {
corrected.

2021-11-16 15:46 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +              )),
all thinks done.

2021-11-16 15:47 UTC, pashabetenya commented on lib/ui/pages/forgot_password_page.dart
> +        Align(
done.

2021-11-16 17:17 UTC, pashabetenya commented on lib/main.dart
> +              '/LoginPage': (context) => LoginPage(),
done.

2021-11-17 10:30 UTC, pashabetenya commented on lib/ui/widgets/draw_clip_widget.dart
> +import 'package:flutter/material.dart';
done.

2021-11-18 07:25 UTC, qkul commented on lib/ui/widgets/draw_clip_widget.dart
> +class DrawClipWidget extends StatefulWidget {
rename all widget without a word Widget

2021-11-18 07:26 UTC, qkul commented on lib/ui/widgets/draw_clip_widget.dart
> +import 'package:flutter/material.dart';
why you use path with ./ ? I think you can use without ./

2021-11-18 07:55 UTC, qkul requested changes

2021-11-18 07:55 UTC, qkul commented on lib/core/const/routes.dart
> +import 'package:cryptocurrency/ui/pages/index.dart';
move for example to config/routes.dart

2021-11-18 07:55 UTC, qkul commented on lib/core/const/routes.dart
> +final Map<String, WidgetBuilder> routes = {
class Routes {
  static const forgot = '/forgon';
  static const login = '/login';
....
}

2021-11-18 07:55 UTC, qkul commented on lib/ui/pages/auth/login_page.dart
> +  Widget _buildLoginForm() {
let's split this widget

2021-11-18 07:55 UTC, qkul commented on lib/ui/pages/auth/login_page.dart
> +              InputPanel(
it's confusing to me. let's remove widget InputPanel. because this is not an obvious widget. I don't expect him to be able to draw only email/password without confirm password

2021-11-18 07:55 UTC, qkul commented on lib/ui/pages/auth/login_page.dart
> +              Align(
_buildForgotPasswordText

2021-11-18 07:55 UTC, qkul commented on lib/ui/pages/auth/login_page.dart
> +              QuestionPanel(
_buildQuestionPanel

2021-11-18 07:55 UTC, qkul commented on lib/ui/widgets/panels/question_panel_widget.dart
> +  final VoidCallback onPressedMaterialButton;
remove the material button from this widget. this is again not obvious

2021-11-18 07:55 UTC, qkul commented on lib/ui/pages/auth/forgot_password_page.dart
> +              MaterialButtonWidget(
_buildSendButton

2021-11-18 07:55 UTC, qkul commented on lib/ui/pages/auth/forgot_password_page.dart
> +                      },
remove common. I think it will be readable

2021-11-18 07:55 UTC, qkul commented on lib/ui/pages/auth/forgot_password_page.dart
> +              MaterialButtonWidget(
_buildGoBackButton

2021-11-20 07:34 UTC, pashabetenya commented on lib/ui/widgets/draw_clip_widget.dart
> +class DrawClipWidget extends StatefulWidget {
changed it in the last commit. look it up.

2021-11-20 07:35 UTC, pashabetenya commented on lib/ui/widgets/draw_clip_widget.dart
> +import 'package:flutter/material.dart';
corrected.

2021-11-20 07:35 UTC, pashabetenya commented on lib/core/const/routes.dart
> +import 'package:cryptocurrency/ui/pages/index.dart';
corrected.

2021-11-20 07:36 UTC, pashabetenya commented on lib/ui/pages/auth/login_page.dart
> +  Widget _buildLoginForm() {
done.

2021-11-20 07:36 UTC, pashabetenya commented on lib/ui/pages/auth/login_page.dart
> +              InputPanel(
done.

2021-11-20 07:36 UTC, pashabetenya commented on lib/ui/pages/auth/login_page.dart
> +              Align(
done.

2021-11-20 07:36 UTC, pashabetenya commented on lib/ui/pages/auth/login_page.dart
> +              QuestionPanel(
done.

2021-11-20 07:36 UTC, pashabetenya commented on lib/ui/widgets/panels/question_panel_widget.dart
> +  final VoidCallback onPressedMaterialButton;
done.

2021-11-20 07:36 UTC, pashabetenya commented on lib/ui/pages/auth/forgot_password_page.dart
> +              MaterialButtonWidget(
done.

2021-11-20 07:36 UTC, pashabetenya commented on lib/ui/pages/auth/forgot_password_page.dart
> +                      },
done.

2021-11-20 07:36 UTC, pashabetenya commented on lib/ui/pages/auth/forgot_password_page.dart
> +              MaterialButtonWidget(
done.

2021-11-21 17:36 UTC, qkul commented on lib/core/const/routes.dart
> +import 'package:cryptocurrency/ui/pages/index.dart';
lib/config/routers.dart

2021-11-21 17:38 UTC, qkul commented on lib/main.dart
> +          initialRoute: '/login',
Routes.login

2021-11-21 17:41 UTC, qkul commented on lib/ui/pages/auth/forgot_password_page.dart
> +        Navigator.pushReplacementNamed(context, '/login');
Navigator.of(context).pushReplacementNamed(Routes.home);

2021-11-21 17:43 UTC, qkul commented on lib/core/config/routes.dart
> +  '/navigation': (context) => ShellPage(),
/shell

2021-11-21 17:46 UTC, qkul commented on lib/ui/pages/auth/login_page.dart
> +          Navigator.pushReplacementNamed(context, '/forgot');
Navigator.of(context).pushReplacementNamed(Routes.forgot);

2021-11-21 17:48 UTC, qkul commented on lib/ui/widgets/buttons/material_button_widget.dart
> +    required this.color,
this.color = Color(0xFF3B77FA)

2021-11-21 17:50 UTC, qkul commented on lib/ui/widgets/common/title_text_widget.dart
> +
remove 7 line

2021-11-21 17:51 UTC, qkul commented on lib/ui/widgets/common/title_text_widget.dart
> +    required this.fontDescriptionSize,
this.fontTitleSize = 35,
this.fontDescriptionSize = 16,

2021-11-21 17:55 UTC, qkul commented on lib/ui/widgets/buttons/text_button_widget.dart
> +class TextButtonWidget extends StatefulWidget {
class TextButton extends StatefulWidget {

2021-11-21 17:56 UTC, qkul commented on lib/ui/widgets/buttons/material_button_widget.dart
> +class MaterialButtonWidget extends StatefulWidget {
class MaterialButton extends StatefulWidget {

2021-11-21 17:56 UTC, qkul commented on lib/ui/widgets/buttons/material_button_widget.dart
> +import 'package:flutter/material.dart';
rename material_button_widget.dart to  material_button.dart

2021-11-21 17:57 UTC, qkul commented on lib/ui/widgets/buttons/text_button_widget.dart
> +import 'package:flutter/material.dart';
text_button.dart

2021-11-21 17:57 UTC, qkul commented on lib/ui/widgets/common/draw_clip_widget.dart
> +import 'package:flutter/material.dart';
draw_clip.dart

2021-11-21 17:57 UTC, qkul commented on lib/ui/widgets/common/title_text_widget.dart
> +import 'package:flutter/material.dart';
also

2021-11-21 17:57 UTC, qkul commented on lib/ui/widgets/fields/email_formfield_widget.dart
> +import 'package:cryptocurrency/generated/locale_keys.g.dart';
also

2021-11-21 17:58 UTC, qkul commented on lib/ui/widgets/fields/password_formfield_widget.dart
> +import 'package:cryptocurrency/generated/locale_keys.g.dart';
also

2021-11-21 17:58 UTC, qkul commented on lib/ui/widgets/panels/bottom_auth_panel_widget.dart
> +import 'package:flutter/material.dart';
also

2021-11-21 17:58 UTC, qkul commented on lib/ui/widgets/panels/question_panel_widget.dart
> +import 'package:cryptocurrency/ui/widgets/index.dart';
also

2021-11-21 18:00 UTC, qkul commented on lib/core/config/routes.dart
> +final Map<String, WidgetBuilder> routes = {
move only string to const.


...
Routes.login: (context) => LoginPage(),
...
return to main.dart

2021-11-21 18:01 UTC, qkul commented on lib/ui/widgets/draw_clip_widget.dart
> +class DrawClipWidget extends StatefulWidget {
the fix is not completely done

2021-11-21 18:06 UTC, qkul commented on lib/ui/widgets/buttons/material_button_widget.dart
> +class MaterialButtonWidget extends StatefulWidget {
why is this widget a StatefulWidget and not a StatelessWidget ?

2021-11-21 18:08 UTC, qkul commented on lib/ui/widgets/buttons/text_button_widget.dart
> +class TextButtonWidget extends StatefulWidget {
why is this widget a StatefulWidget and not a StatelessWidget ?

2021-11-21 18:11 UTC, qkul requested changes

2021-11-21 18:11 UTC, qkul commented on lib/ui/widgets/common/draw_clip_widget.dart
> +class DrawClip extends StatefulWidget {
why is this widget a StatefulWidget and not a StatelessWidget ?

2021-11-21 18:11 UTC, qkul commented on lib/ui/widgets/fields/email_formfield_widget.dart
> +class EmailTextForm extends StatefulWidget {
why is this widget a StatefulWidget and not a StatelessWidget ?

2021-11-25 08:54 UTC, qkul approved these changes

2021-11-25 08:54 UTC, merged