request.
pashabetenya/OPEN-AREA pull request #4
Opened 2021-12-20 13:14 UTC by pashabetenya

2021-12-21 09:57 UTC, qkul requested changes

2021-12-21 09:57 UTC, qkul commented on lib/core/methods/request_currency.dart
> +      'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin%2C%20ethereum%2C%20uniswap%2C%20beam%2C%20tether%2C%20kusama%2C%20avalanche-2%2C%20binancecoin&order=market_cap_desc&
what should I do if I want to pass other parameters to a get request?

2021-12-21 09:57 UTC, qkul commented on lib/core/methods/request_currency.dart
> +import 'dart:async';
bad path lib/core/methods/request_currency.dart. it should be service

2021-12-21 09:59 UTC, qkul commented on lib/core/methods/request_currency.dart
> +      'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin%2C%20ethereum%2C%20uniswap%2C%20beam%2C%20tether%2C%20kusama%2C%20avalanche-2%2C%20binancecoin&order=market_cap_desc&
if you don't want to do extra work, please use https://pub.dev/packages/swagger_dart_code_generator

2021-12-21 17:37 UTC, pashabetenya commented on lib/core/methods/request_currency.dart
> +import 'dart:async';
done.

2021-12-30 15:27 UTC, qkul requested changes

2021-12-30 15:27 UTC, qkul commented on lib/core/services/currency_repository.dart
> +  static final StreamController<List<CurrencyModel>> _controller =
I think it's an overhead. please remove Stream. this is a bad solution and even if it were suitable, we need to take care of controller.close(), since it would continue to use memory.

2021-12-30 15:27 UTC, qkul commented on lib/core/services/currency_repository.dart
> +  static Future<List<CurrencyModel>> fetchCurrencyModel() async {
let's do it not static

2021-12-30 15:27 UTC, qkul commented on lib/core/services/currency_repository.dart
> +      final currency = currencyModelFromJson(response.body);
I think you added stream just to parse response. let's not complicate things and first make jsonDecode and then just map on the model we need and return it

2021-12-30 15:27 UTC, qkul commented on lib/core/services/currency_repository.dart
> +  static Future<List<CurrencyModel>> fetchCurrencyModel() async {
also rename to fetchCurrency

2021-12-30 15:29 UTC, qkul commented
bad description of commits

2022-01-01 13:49 UTC, pashabetenya commented on lib/core/methods/request_currency.dart
> +      'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin%2C%20ethereum%2C%20uniswap%2C%20beam%2C%20tether%2C%20kusama%2C%20avalanche-2%2C%20binancecoin&order=market_cap_desc&
done.

2022-01-04 18:54 UTC, pashabetenya commented on lib/core/services/currency_repository.dart
> +      final currency = currencyModelFromJson(response.body);
done.

2022-01-04 18:55 UTC, pashabetenya commented on lib/core/services/currency_repository.dart
> +  static Future<List<CurrencyModel>> fetchCurrencyModel() async {
done.

2022-01-04 18:55 UTC, pashabetenya commented on lib/core/services/currency_repository.dart
> +  static final StreamController<List<CurrencyModel>> _controller =
done.

2022-01-11 08:05 UTC, qkul approved these changes

2022-01-11 08:06 UTC, merged