architecture block.
pashabetenya/OPEN-AREA pull request #5
Opened 2022-01-11 14:11 UTC by pashabetenya

2022-01-12 07:03 UTC, qkul requested changes

2022-01-17 22:40 UTC, pashabetenya commented on lib/ui/pages/feed/home/currency_item.dart
>  import 'package:flutter/material.dart';
done.

2022-01-17 22:40 UTC, pashabetenya commented on lib/core/bloc/home_page_bloc.dart
> +class HomeStateInit extends HomeState {}
done.

2022-01-17 22:40 UTC, pashabetenya commented on lib/core/bloc/shell_page_bloc.dart
> +abstract class ShellEvent {
done.

2022-01-17 22:40 UTC, pashabetenya commented on lib/core/bloc/home_page_bloc.dart
> +abstract class HomeState {}
done.

2022-01-17 22:41 UTC, pashabetenya commented on lib/core/bloc/shell_page_bloc.dart
> +import 'package:cryptocurrency/core/services/navigation_service.dart';
ok, i get it. i'll try to figure it out and fix it.

2022-01-25 01:06 UTC, pashabetenya commented on lib/core/services/dependency_service.dart
> +GetIt locator = GetIt.instance;
to go back to the old logic that was there before.

2022-01-25 01:07 UTC, pashabetenya commented on lib/core/services/dependency_service.dart
> +  locator.registerLazySingleton(() => NavigationService());
add registration for HomeBloc, ShellBloc.

2022-01-25 01:08 UTC, pashabetenya commented on lib/ui/pages/auth/login_page.dart
> +          _navigationService.navigateTo(Pages.forgot);
to prescribe the same transitions for other pages.

2022-01-25 02:56 UTC, pashabetenya commented on lib/core/services/dependency_service.dart
> +  static void _registerBlocs(GetIt getIt) {
prescribe the architecture (initial) for the authorization pages. start with the login first, and then you will see.

2022-01-25 02:59 UTC, pashabetenya commented on lib/main.dart
> -// import 'package:fluttertoast/fluttertoast.dart';
where did the error message go? what's the point of the cycle in this case..

2022-02-03 23:33 UTC, pashabetenya commented on lib/main.dart
> -// import 'package:fluttertoast/fluttertoast.dart';
done.

2022-02-06 21:41 UTC, merged